sudo: false
language: go
go:
  - 1.14.x

install:
  - go get -u golang.org/x/lint/golint
  - go build -v ./sm2
  - go build -v ./sm3
  - go build -v ./sm4

script:
  - go vet ./sm2
  - go vet ./sm3
  - go vet ./sm4
  - $HOME/gopath/bin/golint .
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - ls /home/travis/gopath/src/
  - go test -v ./sm2
  - go test -v ./sm3
  - go test -v ./sm4
