pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    LTS:
      goVersion: '1.13'
    latest:
      goVersion: '1.14'

steps:
  - task: GoTool@0
    inputs:
      version: $(goVersion)
  - script: go build -v ./sm2
  - script: go build -v ./sm3
  - script: go build -v ./sm4
  - script: go mod vendor
  - script: go vet ./sm2
  - script: go vet ./sm3
  - script: go vet ./sm4
  - script: go get -u golang.org/x/lint/golint; export golint=$(go list -f {{.Target}} golang.org/x/lint/golint); $golint .
    displayName: golint
  - script: go test -v ./...
    displayName: go test recursive